version: '2'

services:

  quexs:
    image: acspri/quexs:remotelime
    ports:
      - 8080:80
    environment:
      QUEXS_DB_PASSWORD: example

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
